# -*- coding: utf-8 -*-
"""Phone pe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9PFGMnrCPNo3qh4X0Gw9jU8wO_FZriq

# PHONE PE

#  LOAD FILES
"""

# Upload JSON files
try:
    from google.colab import files
    uploaded = files.upload()
except ImportError:
    import os
    print("Not running in Colab. Please ensure JSON files are in the working directory.")
    uploaded = {f: f for f in os.listdir() if f.endswith('.json')}
"""# DATA LOADING + CLEANING"""

import json
import pandas as pd

data_list = []

for i, file in enumerate(uploaded.keys()):
    with open(file) as f:
        data = json.load(f)

        users = data['data']['usersByDevice']
        total_users = data['data']['aggregated']['registeredUsers']
        app_opens = data['data']['aggregated']['appOpens']

        for row in users:
            data_list.append({
                "Quarter": f"Q{i+1}",
                "Brand": row['brand'],
                "Count": row['count'],
                "Percentage": row['percentage'],
                "Total_Users": total_users,
                "App_Opens": app_opens
            })

df = pd.DataFrame(data_list)

df.head()

"""# BASIC INFO"""

df.info()
df.describe()
df.isnull().sum()

"""# VISUALIZATIONS

# Chart 1
"""

import matplotlib.pyplot as plt
import seaborn as sns

df.groupby("Brand")["Count"].sum().sort_values().plot(kind='barh')
plt.title("Total Users by Brand")
plt.show()

"""# chart 2"""

df.groupby("Brand")["Percentage"].mean().plot(kind='pie', autopct='%1.1f%%')
plt.title("Market Share by Brand")
plt.show()

"""# chart 3"""

df.groupby("Quarter")["Total_Users"].mean().plot(kind='bar')
plt.title("User Growth per Quarter")
plt.show()

"""# chart 4"""

df.groupby("Quarter")["App_Opens"].mean().plot(marker='o')
plt.title("App Opens Trend")
plt.show()

"""# chart 5"""

sns.barplot(data=df, x="Quarter", y="Count", hue="Brand")
plt.title("Brand Usage per Quarter")
plt.show()

"""# chart 6"""

pivot = df.pivot_table(values="Count", index="Brand", columns="Quarter")
sns.heatmap(pivot, annot=True)
plt.title("Heatmap of Brand Usage")
plt.show()

"""# chart 7"""

df.groupby("Brand")["Count"].sum().nlargest(5).plot(kind='bar')
plt.title("Top 5 Brands")
plt.show()

"""# chart 8"""

df.groupby("Brand")["Count"].sum().nsmallest(5).plot(kind='bar')
plt.title("Bottom 5 Brands")
plt.show()

"""# chart 9"""

sns.histplot(df["Count"], bins=10)
plt.title("Distribution of User Counts")
plt.show()

"""# chart 10"""

sns.boxplot(x="Brand", y="Count", data=df)
plt.xticks(rotation=90)
plt.title("Brand vs Count Distribution")
plt.show()

"""# chart 11"""

sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.title("Correlation Heatmap")
plt.show()

"""# chart 12"""

sns.pairplot(df)
plt.show()

"""# chart 13"""

df.groupby("Quarter")["Total_Users"].mean().pct_change().plot(marker='o')
plt.title("Growth Rate")
plt.show()

"""# chart 14"""

for brand in df["Brand"].unique():
    temp = df[df["Brand"] == brand]
    plt.plot(temp["Quarter"], temp["Count"], label=brand)

plt.legend()
plt.title("Brand Trends Over Time")
plt.show()

"""# chart 15"""

df.groupby("Brand")["Percentage"].mean().sort_values().plot(kind='barh')
plt.title("Average Market Share")
plt.show()

"""# Hypothesis Testing

"""

# Anava

from scipy.stats import f_oneway

groups = [group["Count"].values for name, group in df.groupby("Brand")]
f_stat, p_val = f_oneway(*groups)

print("P-value:", p_val)

# Correlation

from scipy.stats import pearsonr

corr, p_val = pearsonr(df["Total_Users"], df["App_Opens"])

print("Correlation:", corr)
print("P-value:", p_val)

# T Test

from scipy.stats import ttest_ind

q1 = df[df["Quarter"] == "Q1"]["Total_Users"]
q4 = df[df["Quarter"] == "Q4"]["Total_Users"]

t_stat, p_val = ttest_ind(q1, q4)

print("P-value:", p_val)

"""# Preprocessing"""

# Encoding
df_encoded = pd.get_dummies(df, columns=["Brand"])

# Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled = scaler.fit_transform(df[["Count", "Total_Users", "App_Opens"]])

"""# ML Models"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = df[["Count"]]
y = df["App_Opens"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)